### ISSUE TITLE
strabot无法启动

### ISSUE THREAD

**Issue by bayunfenhao** [Starlwr/StarBot#17]
按照教程运行main.py文件报错如下
![图片1](https://github.com/user-attachments/assets/18932e26-0c21-4624-bfca-6d154a7d41e6)

**Comment by Starlwr** [comment]
pip list 核对一下这几个依赖库的版本号
![image](https://github.com/user-attachments/assets/7659148c-3713-46b9-8f46-9deb63e5efa1)
