### ISSUE TITLE
动态报错

### ISSUE THREAD

**Issue by 1753449579** [Starlwr/StarBot#7]
| ERROR    | graia.ariadne.util:126 | Task exception was never retrieved
future: <Task finished name='Task-38' coro=<dynamic_spider() done, defined at /usr/local/lib/python3.10/dist-packages/starbot/core/dynamic.py:13> exception=TypeError("argument of type 'NoneType' is not iterable")>

Traceback (most recent call last):

> File "/usr/local/lib/python3.10/dist-packages/starbot/core/dynamic.py", line 49, in dynamic_spider
    if "new_num" not in latest_dynamic:
                                                   
                        └ None

TypeError: argument of type 'NoneType' is not iterable
![@5@3$V64}1R{``KH87K7YN](https://github.com/Starlwr/StarBot/assets/90882660/f565a459-1eeb-47c1-bb61-bd5808d495d3)

**Comment by Starlwr** [comment]
https://github.com/Starlwr/StarBot/commit/46c803374817d445dd81f1f3c46188940633e94f 上周已修复，还没有发版，今天会发一版更新
