### ISSUE TITLE
登不上了，登录协议要更新，有参考吗

### ISSUE THREAD

**Issue by smallmayi** [Starlwr/StarBot#8]

**Comment by Starlwr** [comment]
是指这两个命令运行报错吗，还是更新协议后登录不成功
```
protocol sync ANDROID_PHONE
protocol sync ANDROID_PAD
```

**Comment by smallmayi** [comment]
> 是指这两个命令运行报错吗，还是更新协议后登录不成功
> 
> ```
> protocol sync ANDROID_PHONE
> protocol sync ANDROID_PAD
> ```
![image](https://github.com/Starlwr/StarBot/assets/42774709/d82de2de-2caf-469d-8c45-6b18c7da2d10)
![image](https://github.com/Starlwr/StarBot/assets/42774709/5a9d9bca-d106-415a-a368-7fa2219d0c83)
版本过低

**Comment by Starlwr** [comment]
这个是因为登录被风控了，可以尝试换个号，或者升级协议版本

**Comment by Starlwr** [comment]
mirai的登录相关问题不属于这个项目，相关问题可以来群里讨论：799915082，有些群友比较有经验
